import type { ChildrenProps } from "@/interfaces";
import RootLayout from "@/layouts/Root";
import { getMe } from "@/modules/user/action";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Forum Gamers",
  description: "Generated by create next app",
};

export default async function Layout({ children }: Readonly<ChildrenProps>) {
  const { error, data } = await getMe();
  if (error || !data) redirect("/login");

  return <RootLayout user={data}>{children}</RootLayout>;
}
